name: Contribution Dashboard
on:
  schedule:
    - cron: '0 15 * * *' # More info: https://crontab.guru/
  workflow_dispatch:

jobs:
  aggregate:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Issues using External Action
        uses: leftkats/issue-finder@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repositories: |
            - datadog/orchestrion
            - jackc/pgx
            - orca-so/whirlpools
            - grafana/grafana
          labels: |
            - good first issue
